name: Playwright Tests Affected
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test-ui-qa-affected:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ENV: QA
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run affected UI Playwright tests in QA environment
      run: npx playwright test --grep @ui --only-changed=$GITHUB_BASE_REF
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-qa
        path: playwright-report/
        retention-days: 30

  test-ui-prod-affected:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      ENV: PROD
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run UI Playwright tests in Production environment
      run: npx playwright test --grep @ui --only-changed=$GITHUB_BASE_REF
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-prod
        path: playwright-report/
        retention-days: 30

  test-api-affected:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run API Playwright tests
      run: npx playwright test --grep @api --only-changed=$GITHUB_BASE_REF
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-api
        path: playwright-report/
        retention-days: 30
