name: Playwright Tests Affected
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  test-api-affected:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set remote to origin
      run: git remote set-url origin https://github.com/tatyana-volovk/pw-training-nx.git
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Calculate changed ref 
      run: echo "changed_ref=$([[ -n "${GITHUB_BASE_REF}" ]] && echo "origin/${GITHUB_BASE_REF}" || echo "HEAD~")" >> "$GITHUB_ENV"
    - name: Run API Playwright tests
      run: npx playwright test --grep @api --only-changed=$changed_ref
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-api
        path: playwright-report/
        retention-days: 30
  test-ui-affected:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [QA, PROD]
    env:
      ENV: ${{ matrix.environment }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set remote to origin
      run: git remote set-url origin https://github.com/tatyana-volovk/pw-training-nx.git
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps chromium webkit
    - name: Calculate changed ref 
      run: echo "changed_ref=$([[ -n "${GITHUB_BASE_REF}" ]] && echo "origin/${GITHUB_BASE_REF}" || echo "HEAD~")" >> "$GITHUB_ENV"
    - name: Run affected UI Playwright tests
      run: npx playwright test --grep @ui --only-changed=$changed_ref
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report-ui-${{ matrix.environment }}
        path: playwright-report/
        retention-days: 30
