name: UI Playwright Tests in different browsers and environments
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        options:
          - qa
          - prod
      project:
        description: 'Browser project to run tests against'
        required: true
        type: choice
        options:
          - chromium
          - webkit
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run UI Playwright tests in ${{github.event.inputs.environment}} in ${{ github.event.inputs.project }} browser
      run: $env:ENV='${{github.event.inputs.environment}}'; npx playwright test --project=${{ github.event.inputs.project }} --grep @ui
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
