name: UI Playwright Tests in different browsers and environments
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        type: choice
        options:
          - QA
          - PROD
      project:
        description: 'Browser project to run tests against'
        required: true
        type: choice
        options:
          - chromium
          - webkit
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps ${{ github.event.inputs.project }}
    - name: Run UI Playwright tests in ${{ github.event.inputs.environment }} on ${{ github.event.inputs.project }}
      env:
        ENV: ${{ github.event.inputs.environment }}
      run: npx playwright test --project=${{ github.event.inputs.project }} --grep @ui
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
